package com.venom.vclient.ui

/** In-app strings (ar / en). The UI is fully RTL in Arabic. */
object S {
    private val ar = mapOf(
        "app.tagline" to "عميل بيئة معزولة",
        "nav.home" to "الرئيسية",
        "nav.profiles" to "البروفايلات",
        "nav.mods" to "المودز",
        "nav.accounts" to "الحسابات",
        "nav.settings" to "الإعدادات",
        "nav.news" to "الأخبار",
        "status.online" to "متصل — جاهز",
        "status.offline" to "بدون إنترنت (محرك V يعمل)",

        "home.launch" to "تشغيل",
        "home.stop" to "إيقاف",
        "home.cancel" to "إلغاء",
        "home.profile" to "البروفايل",
        "home.account" to "الحساب",
        "home.version" to "الإصدار",
        "home.memory" to "الذاكرة",
        "home.lastLaunch" to "آخر تشغيل",
        "home.never" to "—",
        "home.envDesc" to "بيئة معزولة كاملة — ملفات، مكتبات، جلسة وحفظ مستقلين",
        "home.noProfileTitle" to "ما فيك بروفايل",
        "home.noProfileDesc" to "اعمل أول بروفايل — هتتولد له بيئة معزولة كاملة",
        "home.createProfile" to "إنشاء بروفايل",
        "home.runningTitle" to "اللعبة شغالة في بيئة معزولة",
        "home.launching" to "جاري التشغيل…",
        "home.stopped" to "انتهت الجلسة",
        "home.failed" to "فشل التشغيل",
        "home.dryrunTitle" to "Termux مش مثبّت",
        "home.dryrunDesc" to "ماينكرافت جاڤا بتشتغل جوه Termux. ثبّته من F-Droid وعاود التشغيل — أمر التشغيل كامل اتحفظ في reports/last-launch.txt",
        "home.isolated" to "بيئة معزولة",
        "home.latest" to "الأحدث",
        "home.envProcess" to "العملية",
        "home.envData" to "البيانات",
        "home.envSession" to "الجلسة",

        "stage.queued" to "في الطابور",
        "stage.validate" to "تفحص",
        "stage.environment" to "تهيئة البيئة",
        "stage.install" to "تثبيت المحرك",
        "stage.session" to "الجلسة",
        "stage.launch" to "تشغيل",
        "stage.running" to "يعمل الآن",
        "stage.manifest" to "قائمة الإصدارات",
        "stage.version" to "ملف الإصدار",
        "stage.libraries" to "المكتبات",
        "stage.client" to "ملف اللعبة",
        "stage.assets" to "الأصول",
        "stage.natives" to "المكتبات الأصلية",

        "profiles.title" to "بروفايلات",
        "profiles.new" to "بروفايل جديد",
        "profiles.empty" to "مفيش بروفايلات",
        "profiles.emptyDesc" to "كل بروفايل = بيئة معزولة كاملة بملفاتها وسجلاتها",
        "profiles.name" to "الاسم",
        "profiles.engine" to "المحرك",
        "profiles.version" to "الإصدار",
        "profiles.desc" to "وصف",
        "profiles.create" to "إنشاء",
        "profiles.delete" to "حذف",
        "profiles.deleteConfirm" to "هتحذف البروفايل وكل البيئة المعزولة فيه نهائياً",
        "profiles.size" to "الحجم",
        "profiles.launches" to "مرات التشغيل",
        "profiles.last" to "آخر تشغيل",
        "profiles.envTitle" to "بنية البيئة المعزولة",
        "profiles.vengineName" to "محرك V الداخلي",
        "profiles.minecraftName" to "ماينكرافت جاڤا (Termux)",
        "profiles.vengineDesc" to "محرك مدمج — بيئة معزولة كاملة بدون إنترنت",
        "profiles.minecraftDesc" to "manifest ← libraries ← assets ← أمر تشغيل",

        "mods.title" to "المودز",
        "mods.note" to "المودز بتتوضع جوه بيئة البروفايل المعزولة (mods/)",
        "mods.empty" to "مفيش مودز",
        "mods.emptyDesc" to "ارفع ملفات .jar — المحرك هيقرأها من بيئة البروفايل",
        "mods.upload" to "رفع",
        "mods.enabled" to "مفعل",
        "mods.disabled" to "معطل",
        "mods.remove" to "إزالة",

        "accounts.title" to "الحسابات",
        "accounts.offline" to "حساب Offline",
        "accounts.offlineDesc" to "UUID بيتشتق من الاسم (name-hash)",
        "accounts.name" to "اسم المستخدم",
        "accounts.add" to "إضافة",
        "accounts.empty" to "مفيش حسابات",
        "accounts.emptyDesc" to "ضيف حساب Offline الأول",
        "accounts.type" to "النوع",
        "accounts.selected" to "المستخدم",
        "accounts.remove" to "حذف",

        "settings.title" to "الإعدادات",
        "settings.language" to "اللغة",
        "settings.theme" to "الثيم",
        "settings.themeVenom" to "Venom (بنفسجي)",
        "settings.themeToxic" to "Toxic (أخضر)",
        "settings.memMax" to "الحد الأقصى (MB)",
        "settings.memMin" to "الحد الأدنى (MB)",
        "settings.assetMode" to "وضع الأصول",
        "settings.assetShared" to "كاش مشترك",
        "settings.assetIsolated" to "عزل تام",
        "settings.msClient" to "Microsoft client id",
        "settings.msClientDesc" to "مطلوب لتسجيل Microsoft (Azure Portal + scope XboxLive.signin)",
        "settings.dataRoot" to "مجلد البيانات",
        "settings.save" to "حفظ",
        "settings.termuxTitle" to "Minecraft جاڤا على أندرويد",
        "settings.termuxDesc" to "V Client بيبني بيئة اللعبة كاملة جوه البروفايل ويبعت أمر التشغيل لـ Termux. ثبّت Termux من F-Droid.",

        "news.title" to "الأخبار",
        "news.isolationTitle" to "إزاي البيئة المعزولة شغالة",
        "news.isolationDesc" to "كل بروفايل في مجلده الخاص، وعمليته الخاصة، وجلساته الخاصة.",
        "news.process" to "عزل العملية",
        "news.processDesc" to "جلسة منفصلة لكل بروفايل — تقدر تشغل أكتر من بروفايل في نفس الوقت",
        "news.data" to "عزل البيانات",
        "news.dataDesc" to "كل ملفات اللعبة والسففت والمودز جوه مجلد البروفايل",
        "news.session" to "عزل الجلسة",
        "news.sessionDesc" to "التوكن والـ UUID بيتكتبوا جوه بيئة البروفايل (auth/session.json)",
        "news.legal" to "V Client مشروع شخصي (VENOM-P2-GM). ملفات اللعبة بتنزل من خوادم Mojang الرسمية.",
        "news.treeTitle" to "شكل البيئة المعزولة",

        "common.confirm" to "تأكيد",
        "common.cancel" to "إلغاء",
        "common.loading" to "جاري التحميل…",
        "common.version" to "الإصدار",
        "common.engine" to "المحرك",
        "common.delete" to "حذف",
        "common.save" to "حفظ",
        "common.error" to "خطأ",

        "engine.mine" to "Minecraft Java",
        "engine.demo" to "V-Engine"
    )

    private val en = mapOf(
        "app.tagline" to "isolated environment client",
        "nav.home" to "Home",
        "nav.profiles" to "Profiles",
        "nav.mods" to "Mods",
        "nav.accounts" to "Accounts",
        "nav.settings" to "Settings",
        "nav.news" to "News",
        "status.online" to "online — ready",
        "status.offline" to "offline (V-Engine works)",

        "home.launch" to "Launch",
        "home.stop" to "Stop",
        "home.cancel" to "Cancel",
        "home.profile" to "Profile",
        "home.account" to "Account",
        "home.version" to "Version",
        "home.memory" to "Memory",
        "home.lastLaunch" to "Last launch",
        "home.never" to "—",
        "home.envDesc" to "A fully isolated environment — its own files, libraries, session and saves",
        "home.noProfileTitle" to "No profile yet",
        "home.noProfileDesc" to "Create your first profile — a full isolated environment is generated for it",
        "home.createProfile" to "Create profile",
        "home.runningTitle" to "Game running in an isolated environment",
        "home.launching" to "Launching…",
        "home.stopped" to "Session ended",
        "home.failed" to "Launch failed",
        "home.dryrunTitle" to "Termux not installed",
        "home.dryrunDesc" to "Minecraft Java runs inside Termux. Install it from F-Droid and launch again — the full command is saved in reports/last-launch.txt",
        "home.isolated" to "isolated environment",
        "home.latest" to "Latest",
        "home.envProcess" to "Process",
        "home.envData" to "Data",
        "home.envSession" to "Session",

        "stage.queued" to "queued",
        "stage.validate" to "validate",
        "stage.environment" to "environment",
        "stage.install" to "install engine",
        "stage.session" to "session",
        "stage.launch" to "launch",
        "stage.running" to "running",
        "stage.manifest" to "version manifest",
        "stage.version" to "version JSON",
        "stage.libraries" to "libraries",
        "stage.client" to "client jar",
        "stage.assets" to "assets",
        "stage.natives" to "natives",

        "profiles.title" to "Profiles",
        "profiles.new" to "New profile",
        "profiles.empty" to "No profiles",
        "profiles.emptyDesc" to "Each profile is a complete isolated environment with its own files and logs",
        "profiles.name" to "Name",
        "profiles.engine" to "Engine",
        "profiles.version" to "Version",
        "profiles.desc" to "Description",
        "profiles.create" to "Create",
        "profiles.delete" to "Delete",
        "profiles.deleteConfirm" to "This deletes the profile and its entire isolated environment",
        "profiles.size" to "Size",
        "profiles.launches" to "Launches",
        "profiles.last" to "Last launch",
        "profiles.envTitle" to "Isolated environment layout",
        "profiles.vengineName" to "V-Engine (built-in)",
        "profiles.minecraftName" to "Minecraft Java (Termux)",
        "profiles.vengineDesc" to "Built-in engine — full isolated environment, no internet needed",
        "profiles.minecraftDesc" to "manifest ← libraries ← assets ← launch command",

        "mods.title" to "Mods",
        "mods.note" to "Mods live inside the selected profile’s isolated environment (mods/)",
        "mods.empty" to "No mods",
        "mods.emptyDesc" to "Upload .jar files — the engine reads them from the profile environment",
        "mods.upload" to "Upload",
        "mods.enabled" to "enabled",
        "mods.disabled" to "disabled",
        "mods.remove" to "Remove",

        "accounts.title" to "Accounts",
        "accounts.offline" to "Offline account",
        "accounts.offlineDesc" to "UUID derived from the username (name-hash)",
        "accounts.name" to "Username",
        "accounts.add" to "Add",
        "accounts.empty" to "No accounts",
        "accounts.emptyDesc" to "Add an offline account first",
        "accounts.type" to "Type",
        "accounts.selected" to "In use",
        "accounts.remove" to "Remove",

        "settings.title" to "Settings",
        "settings.language" to "Language",
        "settings.theme" to "Theme",
        "settings.themeVenom" to "Venom (purple)",
        "settings.themeToxic" to "Toxic (green)",
        "settings.memMax" to "Max memory (MB)",
        "settings.memMin" to "Min memory (MB)",
        "settings.assetMode" to "Assets mode",
        "settings.assetShared" to "Shared cache",
        "settings.assetIsolated" to "Strict isolation",
        "settings.msClient" to "Microsoft client id",
        "settings.msClientDesc" to "Required for Microsoft sign-in (Azure Portal + XboxLive.signin scope)",
        "settings.dataRoot" to "Data folder",
        "settings.save" to "Save",
        "settings.termuxTitle" to "Minecraft Java on Android",
        "settings.termuxDesc" to "V Client builds the whole game environment inside the profile and sends the launch command to Termux. Install Termux from F-Droid.",

        "news.title" to "News",
        "news.isolationTitle" to "How the isolated environment works",
        "news.isolationDesc" to "Each profile lives in its own folder, with its own process and session.",
        "news.process" to "Process isolation",
        "news.processDesc" to "A separate session per profile — run several profiles at once",
        "news.data" to "Data isolation",
        "news.dataDesc" to "All game files, saves and mods live inside the profile folder",
        "news.session" to "Session isolation",
        "news.sessionDesc" to "The token & UUID are written inside the profile environment (auth/session.json)",
        "news.legal" to "V Client is a personal project (VENOM-P2-GM). Game files come from Mojang’s official servers.",
        "news.treeTitle" to "Isolated environment layout",

        "common.confirm" to "Confirm",
        "common.cancel" to "Cancel",
        "common.loading" to "Loading…",
        "common.version" to "Version",
        "common.engine" to "Engine",
        "common.delete" to "Delete",
        "common.save" to "Save",
        "common.error" to "Error",

        "engine.mine" to "Minecraft Java",
        "engine.demo" to "V-Engine"
    )

    fun t(lang: String, key: String): String =
        (if (lang == "ar") ar else en)[key] ?: en[key] ?: key
}
